name: Mirror Marameo FAIR Tool

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout marameo-fairtool branch
        uses: actions/checkout@v3
        with:
          ref: marameo-fairtool
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Mirror Bot"
          git config --global user.email "noreply@github.com"

      - name: Download source repo using GitHub API
        run: |
          mkdir -p temp
          cd temp

          # First check access to the repository
          curl -s -o api_response.json -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            https://api.github.com/repos/marameodesignteam/ardc-new

          # Show the response for debugging
          cat api_response.json

          # Now try to download the zip
          curl -v -L -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -o repo.zip \
            https://api.github.com/repos/marameodesignteam/ardc-new/zipball/master

          # Check if download was successful
          if [ -f repo.zip ] && [ $(stat -c%s repo.zip) -gt 1000 ]; then
            echo "Successfully downloaded repository zip"

            # Extract the zip file
            unzip -q repo.zip

            # Find the extracted directory (it has a dynamic name with commit hash)
            EXTRACT_DIR=$(ls -d marameodesignteam-ardc-new-* 2>/dev/null | head -n 1)

            if [ -n "$EXTRACT_DIR" ]; then
              # Move contents to a predictable name
              mkdir -p ardc-new
              mv $EXTRACT_DIR/* ardc-new/
            else
              echo "Failed to extract repository or find extracted directory"
              exit 1
            fi
          else
            echo "Failed to download repository zip. Checking file content:"
            cat repo.zip
            exit 1
          fi

      - name: Extract and update FAIR tool components
        if: success()
        run: |
          # Remove everything except .git
          find . -mindepth 1 -maxdepth 1 -not -name '.git' -not -name 'temp' -exec rm -rf {} \;

          # Create directory structure and copy files
          mkdir -p wp-content/plugins
          mkdir -p wp-content/themes/ardc/gutenberg/blocks
          mkdir -p wp-content/themes/ardc/template-parts/blocks
          mkdir -p wp-content/themes/ardc/js
          mkdir -p wp-content/themes/ardc/css

          # Copy plugin files if they exist
          if [ -d "temp/ardc-new/wp-content/plugins/mmd-fair-tool" ]; then
            cp -r temp/ardc-new/wp-content/plugins/mmd-fair-tool wp-content/plugins/
          else
            echo "Plugin directory not found"
            exit 1
          fi

          # Copy Gutenberg blocks
          cp -r temp/ardc-new/wp-content/themes/ardc/gutenberg/blocks/fair-tool* wp-content/themes/ardc/gutenberg/blocks/ || echo "Gutenberg blocks not found"

          # Copy template parts
          cp -r temp/ardc-new/wp-content/themes/ardc/template-parts/blocks/fair-tool* wp-content/themes/ardc/template-parts/blocks/ || echo "Template parts not found"

          # Copy JS and CSS
          cp temp/ardc-new/wp-content/themes/ardc/js/fair-tool.js wp-content/themes/ardc/js/ || echo "JS file not found"
          cp temp/ardc-new/wp-content/themes/ardc/css/fairtool.css* wp-content/themes/ardc/css/ 2>/dev/null || echo "CSS file not found"

          # Create README with source information
          echo "# FAIR Tool WordPress Plugin and Theme Components" > README.md
          echo "" >> README.md
          echo "This branch contains FAIR Tool components extracted from the [Marameo ARDC site repository](https://github.com/marameodesignteam/ardc-new)." >> README.md
          echo "" >> README.md
          echo "Last updated: $(date)" >> README.md
          echo "" >> README.md
          echo "## Structure" >> README.md
          echo "- Plugin code: \`wp-content/plugins/mmd-fair-tool/\`" >> README.md
          echo "- Theme components: \`wp-content/themes/ardc/\`" >> README.md

          # Commit changes if any
          git add -A
          git diff --staged --quiet || git commit -m "Update FAIR Tool components from marameo repository $(date -u)"

          # Push to branch
          git push
